[package]
name = "game-movement-copy"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty-xinput = "1.3.0"
vigem-client = "0.1.4"
rdev = { version = "0.5.3", features = ["serialize"] }

serde = { version = "1.0.216", features = ["derive"] }
serde_yml = "0.0.12"
