config:
  interval: 10.0
  enable_mouse: true
  enable_keyboard: true
  enable_controller:
  - true
  - false
  - false
  - false
  start_record_button: !Contains
  - key: Return
    controller_btn: null
    ctrl: false
    alt: false
    shift: true
    tab: false
    windows: false
    mouse_l_button: null
    mouse_r_button: null
    mouse_m_button: null
    trigger_l: null
    trigger_r: null
  stop_record_button: !Contains
  - key: Escape
    controller_btn: null
    ctrl: false
    alt: false
    shift: false
    tab: false
    windows: false
    mouse_l_button: null
    mouse_r_button: null
    mouse_m_button: null
    trigger_l: null
    trigger_r: null
  start_playback_button: !Contains
  - key: Return
    controller_btn: null
    ctrl: true
    alt: false
    shift: false
    tab: false
    windows: false
    mouse_l_button: null
    mouse_r_button: null
    mouse_m_button: null
    trigger_l: null
    trigger_r: null
  stop_playback_button: !Contains
  - key: Escape
    controller_btn: null
    ctrl: false
    alt: false
    shift: false
    tab: false
    windows: false
    mouse_l_button: null
    mouse_r_button: null
    mouse_m_button: null
    trigger_l: null
    trigger_r: null
  continue_record_button: !Exclude
  - key: Escape
    controller_btn: null
    ctrl: false
    alt: false
    shift: false
    tab: false
    windows: false
    mouse_l_button: null
    mouse_r_button: null
    mouse_m_button: null
    trigger_l: null
    trigger_r: null
  drop_record_button: !Contains
  - key: Escape
    controller_btn: null
    ctrl: false
    alt: false
    shift: true
    tab: false
    windows: false
    mouse_l_button: null
    mouse_r_button: null
    mouse_m_button: null
    trigger_l: null
    trigger_r: null
init_state:
  time_ms: 0.0
  pressed_keys: []
  offsets:
    mouse:
    - 0.0
    - 0.0
    wheel:
    - 0.0
    - 0.0
    trigger:
    - - 0.0
      - 0.0
    - - 0.0
      - 0.0
    - - 0.0
      - 0.0
    - - 0.0
      - 0.0
    sticks:
    - - 0.0
      - 0.0
      - 0.0
      - 0.0
    - - 0.0
      - 0.0
      - 0.0
      - 0.0
    - - 0.0
      - 0.0
      - 0.0
      - 0.0
    - - 0.0
      - 0.0
      - 0.0
      - 0.0
records: []
